name: "Deploy Function App"
on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.head_ref ||  github.ref }}

permissions: # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  function-deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt --target="app/.python_packages/lib/site-packages"

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.FUNCTION_NAME }}
          package: './app'